import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Header from "@/src/composants/Header";
import Footer from "@/src/composants/Footer";

const avallonFont = localFont({
  src: './fonts/Avallon.woff2',
  variable: '--font-avallon',
})

const quicksandFont = localFont({
  src: './fonts/Quicksand-VariableFont_wght.ttf',
  variable: '--font-text'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${avallonFont.variable} ${quicksandFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <Footer />
      </body>


    </html>
  );
}
