import { Injectable, NotFoundException } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { ColorEntity } from "../../entities/color.entity";
import { MaterialEntity } from "../../entities/material.entity";
import { ProductEntity } from "../../entities/product.entity";
import { StockEntity } from "../../entities/stock.entity";
import { SubcategoryEntity } from "../../entities/subcategory.entity";

/**
 * Service for managing product stock/inventory operations including SKU generation.
 * Handles stock creation, updates, and deletion across products, colors, materials, and categories.
 */
@Injectable()
export class StockService {
    /**
     * Injects repositories for all entities used in stock management operations.
     * @param stockRepository - Repository for StockEntity CRUD operations.
     * @param productRepository - Repository for ProductEntity lookups during stock creation.
     * @param colorRepository - Repository for ColorEntity lookups.
     * @param materialRepository - Repository for MaterialEntity lookups.
     * @param subcategoryRepository - Repository for SubcategoryEntity with category relations.
     */
    constructor(
        @InjectRepository(StockEntity)
        private readonly stockRepository: Repository<StockEntity>,

        @InjectRepository(ProductEntity)
        private readonly productRepository: Repository<ProductEntity>,

        @InjectRepository(ColorEntity)
        private readonly colorRepository: Repository<ColorEntity>,

        @InjectRepository(MaterialEntity)
        private readonly materialRepository: Repository<MaterialEntity>,

        @InjectRepository(SubcategoryEntity)
        private readonly subcategoryRepository: Repository<SubcategoryEntity>
    ){}

    /**
     * Retrieves all stock records with fully populated relations.
     * @returns An array of StockEntity instances including color, material, and product details.
     * @throws NotFoundException - If no stock records are found.
     */
    async getAllStock() {
        const stocks = await this.stockRepository.find({ relations: ["color", "material", "product"]})

        if(!stocks){
            throw new NotFoundException
        }

        return stocks        
    }

    /**
     * Retrieves a specific stock record by its SKU code with full relation data.
     * @param stockSku - The unique SKU identifier of the stock entry to retrieve.
     * @returns The StockEntity with populated color, material, and product relations.
     * @throws NotFoundException - If no stock exists with the given SKU.
     */
    async getStockBySku(stockSku: string) {
        const stock = await this.stockRepository.findOne({ where: {sku: stockSku}, relations: ["color", "material", "product"]})

        if(!stock){
            throw new NotFoundException
        }

        return stock
    }

    /**
     * Retrieves a specific stock record by its unique database ID.
     * @param stockId - The unique identifier of the stock entry to retrieve.
     * @returns The StockEntity with populated color, material, and product relations.
     * @throws NotFoundException - If no stock exists with the given ID.
     */
    async getStockById(stockId: number){
        const stock =  await this.stockRepository.findOne({where: {id: stockId}, relations: ["color", "material", "product"]})

        if(!stock){
            throw new NotFoundException
        }

        return stock
    }

    /**
     * Creates a new stock entry with automatic SKU code generation.
     * The SKU is generated by combining product, category, subcategory, color, and material codes.
     * @param quantity - The number of units to add to inventory.
     * @param productId - The ID of the product this stock belongs to.
     * @param colorId - The ID of the color variant.
     * @param materialId - The ID of the material used in construction.
     * @param subcategoryId - The ID of the subcategory (needed for SKU generation).
     * @returns The newly created StockEntity with populated relations.
     * @throws NotFoundException - If any required entity (color, material, product, subcategory) is not found.
     */
    async addStock(quantity: number, productId: number, colorId: number, materialId: number, subcategoryId: number){
        const color = await this.colorRepository.findOne({ where: {id: colorId}})
        const material = await this.materialRepository.findOne({ where: {id: materialId}})
        const product = await this.productRepository.findOne({ where: {id: productId}})
        const subcategory = await this.subcategoryRepository.findOne({ where: {id: subcategoryId}, relations: ["category"]})

        if(!color || !material || !product || !subcategory){
            throw new NotFoundException
        }

        const colorSkuCode = color.sku_code
        const materialSkuCode = material.sku_code
        const productSkuCode = product.sku_code
        const subcategorySkuCode = subcategory.sku_code
        const categorySkuCode = subcategory.category.sku_code

        const stockSkuCode = productSkuCode + "_" + categorySkuCode + "_" + subcategorySkuCode + "_" + colorSkuCode + "_" + materialSkuCode

        const stock = this.stockRepository.create({
           quantity: quantity,
           product: product,
           material: material,
           color: color,
           sku: stockSkuCode
        })
        
        const savedStock = await this.stockRepository.save(stock)

        return this.getStockBySku(savedStock.sku)
    }

    /**
     * Updates the quantity of an existing stock entry.
     * @param quantity - The new quantity to set for this stock SKU.
     * @param stockSku - The unique SKU identifier of the stock entry to update.
     * @returns The updated StockEntity with populated relations.
     * @throws NotFoundException - If no stock exists with the given SKU.
     */
    async updateStock(quantity: number, stockSku: string) {
        const stock = await this.stockRepository.findOne({ where: {sku: stockSku}})

        if(!stock){
            throw new NotFoundException
        }

        stock.quantity = quantity
        const updatedStock = await this.stockRepository.save(stock)

        return this.getStockBySku(updatedStock.sku)
    }

    /**
     * Deletes a stock entry by its SKU code or removes all stocks for a product.
     * @param stockSku - The unique SKU identifier of the stock to delete. If omitted, removes all stocks for a given product.
     * @throws NotFoundException - If no stock exists with the given SKU.
     */
    async deleteStockByProductId(stockSku?: string){
        const stock = await this.stockRepository.findOne({ where: {sku: stockSku}})

        if(!stock){
            throw new NotFoundException
        }

        await this.stockRepository.remove(stock)
    }
}